![imagen de numpy](assets/NumPy.png)


Numpy es una librería de Python desarrollada para trabajar con operaciones matemáticas relacionadas al álgebra lineal, es decir, para representar valores numéricos a través de vectores y matrices.

Para ello, Numpy cuenta con una 'estructura de datos' propia llamada **Array**(*Arreglos*). Inicialmente nosotros podríamos representar estas estructuras matemáticas en listas (Vectores) o listas de listas (Matrices), sin embargo la lista de Python posee una limitante, y es que no cuenta con ciertas operaciones matemáticas que los arreglos de Numpy si poseen, y esto es lo que veremos a continuación.

Más información en: https://numpy.org/devdocs/dev/internals.html

In [2]:
import numpy as np

#### Tip: En el contexto de las ciencia de datos, siempre llamaremos las librerías con abreviaturas. En el caso de Numpy solemos llamarlo np.

## 1. Construcción de un Array

Los array siguen la misma lógica que los vectores y matrices. Así podemos definir un array como una matriz de elementos que satisface:

<img src="assets/matrix_def.png" alt="Descripción de la imagen" width="700" height="400">


Para Numpy: 

Cada lista anidada ingresada al array representa una fila, Luego construimos las columnas en función de las filas ingresadas.


In [17]:
#vector de una dimension
a1 = np.array([1,2,3,4])
print(a1)

[1 2 3 4]


In [16]:
a1_columna = np.array([[1], [2], [3], [4]])
print(a1_columna)

[[1]
 [2]
 [3]
 [4]]


In [11]:
#matriz de dos dimensiones
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
#Matriz cuadrada de 3x3
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2. Dimensionalidad de un array

Como toda matriz, un array posee dimensiones. Estas las podemos encontrar usando **.shape**

In [19]:
a1.shape

(4,)

In [18]:
a1_columna.shape

(4, 1)

In [15]:
a2.shape

(2, 5)

In [20]:
a3.shape

(3, 3)

## 3. Operaciones matemáticas de un array

**Suma de arrays**

In [21]:
suma = a1 + a1
print(suma)

[2 4 6 8]


¿Puedo sumar arrays con distintas dimensiones?

In [22]:
a1_columna + a1


array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

In [28]:
#Definamos dos matrices con dimensiones no necesariamente iguales

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

#Intentemos sumarlas
try:
    a + b
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (4,3) 


¿Qué pasó aquí? 

Efectivamente Numpy nos deja sumar arrays con distintas dimensiones, por lo que debemos tener ojo al realizar sumas para ser consistentes con nuestros objetivos y no tener errores. 

**Multiplicación de arrays**

In [24]:
multiplicacion = a1 * a1
print(multiplicacion)

[ 1  4  9 16]


Como observamos la multiplicación funciona como el producto punto, es decir, multiplica componente por componente. 

In [26]:
multiplicacion = a1 * a1_columna
print(multiplicacion)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [29]:
#Intentemos multiplicarlas
try:
    a * b
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,3) (4,3) 


**Multiplicación matricial**

In [34]:
#Intentemos multiplicar a y b matricialmente


try:
    a @ b
except ValueError as e:
    print(e)

print("....................................")

multiplicacion = b @ a
print(multiplicacion)

matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)
....................................
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]
 [138 171 204]]


**Para multiplicar matrices necesitamos que se respete la condición de multiplicación: la dimensión de las columnas de la primera matriz debe coincidir con las filas de la segunda matriz a multiplicar** 

**(Spoiler de algebra lineal: Esto nos da un indicio de que el producto de matrices no es conmutativo)**